name: reviewdog
on:
  pull_request:
    types: [ opened, synchronize ]
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Run reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.SECRET_TOKEN }}
          reporter: github-pr-review
          eslint_flags: './**/*.{vue,ts,js}'
        run: |
          reviewdog -reporter=github-check -runners=eslint
          
