name: reviewdog
on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-eslint@v1

        with:
          reporter: github-pr-review # Change reporter.
          eslint_flags: 'src/'


#
#jobs:
#  eslint:
#    name: eslint
#    runs-on: ubuntu-latest
#    steps:
#      - name: Run reviewdog
#        env:
#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.SECRET_TOKEN }}
#        uses: reviewdog/action-eslint@v1
#        #        with:
#        #          reporter: github-pr-review
#        #          eslint_flags: './**/*.{vue,ts,js}'
#        run: |
#          echo ${{ secrets.SECRET_TOKEN }}
#          reviewdog -reporter=github-check -runners=eslint
#
